STRINGS.SHINOBUTAB = "忍野忍"

STRINGS.NAMES.HEARTSPAN = "妖刀·心渡"
STRINGS.RECIPE_DESC.HEARTSPAN = "很久很久以前的，故人的味道......"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEARTSPAN = "..."

STRINGS.NAMES.KATANA = "无名太刀"
STRINGS.RECIPE_DESC.KATANA = "还凑合吧~"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KATANA = "..."

STRINGS.CHARACTER_TITLES.shinobu = "忍野忍"
STRINGS.CHARACTER_NAMES.shinobu = "忍野忍"
STRINGS.CHARACTER_DESCRIPTIONS.shinobu = "只要甜甜圈存在之一天，吾就不会毁灭人类！"
STRINGS.CHARACTER_QUOTES.shinobu = "咔咔！"

STRINGS.NAMES.shinobu = "忍野忍"

